default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: erp_rails_development

test:
  <<: *default
  database: erp_rails_test

production:
  <<: *default
  database: erp_rails_production
